# Schema for the configuration files of the support ticket module.

support_ticket.settings:
  type: config_object
  label: 'Support ticket settings'
  mapping:
    use_admin_theme:
      type: boolean
      label: 'Use admin theme when editing or creating tickets'
    support_ticket_type_settings:
      type: sequence
      label: 'Support ticket type settings'
      sequence:
        type: support_ticket_type_settings_base
        label: 'Support ticket type'

support_ticket_type_settings_base:
  type: config_entity
  label: 'Support ticket type settings'
  mapping:
    comment_diff_field:
      type: string
      label: 'Diff field'
    comment_diff_revision_reference:
      type: string
      label: 'Diff revision reference field'
    filter_format:
      type: string
      label: 'Filter format for support ticket type.'
    comment_diff_revision_changes:
      type: string
      label: 'Diff revision changes field'

support_ticket.type.*:
  type: config_entity
  label: 'Support ticket type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'
    display_submitted:
      type: boolean
      label: 'Display setting for author and date Submitted by post information'

action.configuration.support_ticket_assign_owner_action:
  type: mapping
  label: 'Change the author of ticket configuration'
  mapping:
    owner_uid:
      type: text
      label: 'Username'

action.configuration.support_ticket_publish_action:
  type: action_configuration_default
  label: 'Publish selected ticket configuration'

action.configuration.support_ticket_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish selected ticket configuration'

action.configuration.support_ticket_save_action:
  type: action_configuration_default
  label: 'Save ticket configuration'

action.configuration.support_ticket_delete_action:
  type: action_configuration_default
  label: 'Delete ticket configuration'

action.configuration.support_ticket_lock_action:
  type: action_configuration_default
  label: 'Make selected ticket locked configuration'

action.configuration.support_ticket_unlock_action:
  type: action_configuration_default
  label: 'Make selected ticket unlocked configuration'

action.configuration.support_ticket_unpublish_by_keyword_action:
  type: mapping
  label: 'Unpublish support tickets containing keyword(s) configuration'
  mapping:
    keyword:
      type: sequence
      label: 'Keywords'
      sequence:
        type: string
        label: 'Keyword'

condition.plugin.support_ticket_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
